image: node:10.13.0

cache:
  key: cache_yarn
  paths:
    - .cache_yarn

stages:
  - install
  - build
  - test
  - deploy

install_api:
  stage: install
  script:
    - cd ./functions && yarn install --cache-folder ../.cache_yarn
  only:
    - merge_requests
    - staging
    - master
  artifacts:
    paths:
      - functions/node_modules

install_web:
  stage: install
  script:
    - cd ./client && yarn install --cache-folder ../.cache_yarn
  only:
    - merge_requests
    - staging
    - master
  artifacts:
    paths:
      - client/node_modules

build_web:
  stage: build
  script:
    - cd ./client && yarn build
  only:
    - merge_requests
    - staging
    - master
  dependencies:
    - install_web
  artifacts:
    paths:
      - client/build

test_web:
  stage: test
  script:
    - cd ./client && yarn test
  only:
    - merge_requests
    - staging
    - master
  dependencies:
    - install_web

deploy_staging:
  stage: deploy
  script:
    - yarn global add firebase-tools --cache-folder ../.cache_yarn
    - firebase use staging
    - firebase functions:config:unset env
    - firebase functions:config:set env.type="staging"
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - staging
  environment:
    name: staging
  dependencies:
    - install_api
    - build_web

deploy_production:
  stage: deploy
  script:
    - yarn global add firebase-tools --cache-folder ../.cache_yarn
    - firebase use production
    - firebase functions:config:unset env
    - firebase functions:config:set env.type="production"
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - master
  environment:
    name: production
  dependencies:
    - install_api
    - build_web
