export const PENDING = "PENDING";
export const FULFILLED = "FULFILLED";
export const REJECTED = "REJECTED";
export const RESET = "RESET";
export const FETCH_RECAPTCHA = "FETCH_RECAPTCHA";
export const SIGN_OUT = "SIGN_OUT";

export const FETCH_SUBMIT = "FETCH_SUBMIT";
export const FETCH_SUBMIT_PENDING = "FETCH_SUBMIT_PENDING";
export const FETCH_SUBMIT_FULFILLED = "FETCH_SUBMIT_FULFILLED";
export const FETCH_SUBMIT_REJECTED = "FETCH_SUBMIT_REJECTED";

export const FETCH_AUTH = "FETCH_AUTH";
export const FETCH_AUTH_PENDING = "FETCH_AUTH_PENDING";
export const FETCH_AUTH_FULFILLED = "FETCH_AUTH_FULFILLED";
export const FETCH_AUTH_REJECTED = "FETCH_AUTH_REJECTED";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_PENDING = "FETCH_CATEGORIES_PENDING";
export const FETCH_CATEGORIES_FULFILLED = "FETCH_CATEGORIES_FULFILLED";
export const FETCH_CATEGORIES_REJECTED = "FETCH_CATEGORIES_REJECTED";

export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_PENDING = "FETCH_COUNTRIES_PENDING";
export const FETCH_COUNTRIES_FULFILLED = "FETCH_COUNTRIES_FULFILLED";
export const FETCH_COUNTRIES_REJECTED = "FETCH_COUNTRIES_REJECTED";

export const FETCH_MERCHANTS = "FETCH_MERCHANTS";
export const FETCH_MERCHANTS_PENDING = "FETCH_MERCHANTS_PENDING";
export const FETCH_MERCHANTS_FULFILLED = "FETCH_MERCHANTS_FULFILLED";
export const FETCH_MERCHANTS_REJECTED = "FETCH_MERCHANTS_REJECTED";

export const FETCH_MERCHANT = "FETCH_MERCHANT";
export const FETCH_MERCHANT_PENDING = "FETCH_MERCHANT_PENDING";
export const FETCH_MERCHANT_FULFILLED = "FETCH_MERCHANT_FULFILLED";
export const FETCH_MERCHANT_REJECTED = "FETCH_MERCHANT_REJECTED";
